/* Automatically generated by po2tbl.sed from yp-tools.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"nickname file %s does not exist.\n", 2},
  {"Bogus entry in line %d: %s\n", 3},
  {"Use \"%s\"\tfor map \"%s\"\n", 4},
  {"Success", 5},
  {"Internal ypbind error", 6},
  {"Domain not bound", 7},
  {"System resource allocation failure", 8},
  {"Unknown ypbind error", 9},
  {"\
Copyright (C) %s Thorsten Kukuk.\n\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 10},
  {"Usage: %s [domain]\n", 11},
  {"\
domainname - set or display name of current domain\n\
\n", 12},
  {"  -?, --help     Give this help list\n", 13},
  {"      --usage    Give a short usage message\n", 14},
  {"      --version  Print program version\n", 15},
  {"\
%s - set or display name of current NIS domain\n\
\n", 16},
  {"Try `%s --help' or `%s --usage' for more information.\n", 17},
  {"Written by %s.\n", 18},
  {"Usage: ypcat [-kt] [-d domain] mapname | -x\n", 19},
  {"\
ypcat - print values of all keys in a NIS database\n\
\n", 20},
  {"  -d domain      Use 'domain' instead of the default domain\n", 21},
  {"  -k             Display map keys\n", 22},
  {"  -t             Inhibits map nickname translation\n", 23},
  {"  -x             Display the map nickname translation table\n", 24},
  {"%s: can't get local yp domain: %s\n", 25},
  {"No running ypbind\n", 26},
  {"No such map %s. Reason: %s\n", 27},
  {"Usage: ypmatch [-d domain] [-kt] key ... mapname | -x\n", 28},
  {"\
ypmatch - print the values of one or more keys from a NIS map\n\
\n", 29},
  {"Can't match key %s in map %s. Reason: %s\n", 30},
  {"Usage: yppasswd [-f] [-l] [-p] [User]\n", 31},
  {"Usage: ypchsh [User]\n", 32},
  {"Usage: ypchfn [User]\n", 33},
  {"\
yppasswd - change your password in the NIS database\n\
\n", 34},
  {"  -f             Change GECOS field information\n", 35},
  {"  -l             Change the login shell\n", 36},
  {"  -p             Change the password\n", 37},
  {"\
ypchsh - change the shell in the NIS database\n\
\n", 38},
  {"\
ypchfn - change the GECOS information in the NIS database\n\
\n", 39},
  {"%s: can't find the master ypserver: %s\n", 40},
  {"%s: yppasswdd not running on NIS master host (\"%s\").\n", 41},
  {"%s: yppasswd daemon running on illegal port (\"%s\").\n", 42},
  {"No more", 43},
  {"True", 44},
  {"False", 45},
  {"No such map", 46},
  {"No such domain", 47},
  {"Bad operation", 48},
  {"Database bad", 49},
  {"Bad arguments", 50},
  {"Version Mismatch", 51},
  {"Unknown error", 52},
  {"%s: no colons allowed in GECOS field... sorry.\n", 53},
  {"The password must have at least 6 characters.\n", 54},
  {"\
The password must have both upper and lowercase letters, or non-letters.\n", 55},
  {"You cannot reuse the old password.\n", 56},
  {"Please don't use something like your username as password.\n", 57},
  {"%s: unknown user (uid=%ld).\n", 58},
  {"%s: Only root may change account information for others\n", 59},
  {"Changing NIS account information for %s on %s.\n", 60},
  {"Please enter root password:", 61},
  {"Please enter %spassword:", 62},
  {"old ", 63},
  {"Sorry.\n", 64},
  {"Changing NIS password for %s on %s.\n", 65},
  {"\
Too many tries. Aborted.\n\
Password unchanged.\n", 66},
  {"Please enter new password:", 67},
  {"Password unchanged.\n", 68},
  {"Not a valid password: %s.\n", 69},
  {"Please retype new password:", 70},
  {"Mismatch - password unchanged.\n", 71},
  {"\
\n\
Changing full name for %s on %s.\n\
To accept the default, simply press return. To enter an empty\n\
field, type the word \"none\".\n", 72},
  {"Name", 73},
  {"Location", 74},
  {"Office Phone", 75},
  {"Home Phone", 76},
  {"\
\n\
Changing login shell for %s on %s.\n\
To accept the default, simply press return. To use the\n\
system's default shell, type the word \"none\".\n", 77},
  {"Login shell", 78},
  {"Error while changing the NIS password.", 79},
  {"\
\n\
The NIS password has not been changed on %s.\n\
\n", 80},
  {"\
\n\
The NIS password has been changed on %s.\n\
\n", 81},
  {"Error while changing the GECOS information.", 82},
  {"\
\n\
The GECOS information has not been changed on %s.\n\
\n", 83},
  {"\
\n\
The GECOS information has been changed on %s.\n\
\n", 84},
  {"Error while changing the login shell.", 85},
  {"\
\n\
The login shell has not been changed on %s.\n\
\n", 86},
  {"\
\n\
The login shell has been changed on %s.\n\
\n", 87},
  {"Error while changing the NIS account information.", 88},
  {"\
\n\
The NIS account information has not been changed on %s.\n\
\n", 89},
  {"\
\n\
The NIS account information has been changed on %s.\n\
\n", 90},
  {"Usage: yppoll [-h host] [-d domain] mapname\n", 91},
  {"\
yppoll - return version and master server of a NIS map\n\
\n", 92},
  {"  -h host        Ask ypserv process at 'host'\n", 93},
  {"Couldn't get NIS server", 94},
  {" - ypbind not running ?\n", 95},
  {"Unknown host: %s\n", 96},
  {"Host name lookup failure\n", 97},
  {"No address associated with name: %s\n", 98},
  {"Unknown server error\n", 99},
  {"gethostbyname: Unknown error\n", 100},
  {"Can't create connection to %s.\n", 101},
  {"Reason", 102},
  {"Domain %s is not supported by %s.\n", 103},
  {"Can't get any map parameter information.\n", 104},
  {"Domain %s is supported.\n", 105},
  {"Can't get order number for map %s.\n", 106},
  {"\tReason: %s\n", 107},
  {"Map %s has order number %d. [%s]\n", 108},
  {"Can't get master for map %s.\n", 109},
  {"The master server is %s.\n", 110},
  {"Usage: ypset [-d domain] [-h hostname] server\n", 111},
  {"\
ypset - bind ypbind to a particular NIS server\n\
\n", 112},
  {"  -h hostname    Set ypbind's binding on ´hostname´\n", 113},
  {"%s not running ypserv.\n", 114},
  {"can't find address for %s\n", 115},
  {"can't yp_bind: Reason: %s\n", 116},
  {"Cannot ypset for domain %s on host %s.\n", 117},
  {"ypset: host %s unknown\n", 118},
  {"Usage: ypwhich [-d domain] [[-t] -m [mname]|[-Vn] hostname] | -x\n", 119},
  {"\
ypwhich - return name of NIS server or map master\n\
\n", 120},
  {"  -m mname       Find the master NIS server for the map 'mname'\n", 121},
  {"  -V n           Version of ypbind, V2 is default\n", 122},
  {"Can't find master for map \"%s\". Reason: %s\n", 123},
  {"Can't find master for map %s. Reason: %s\n", 124},
  {"No running ypbind.\n", 125},
  {"Can't get map list for domain %s. Reason: %s\n", 126},
  {"ypwhich: host %s unknown\n", 127},
};

int _msg_tbl_length = 127;
